services:
  frontend:
    build:
      context: ./frontend
      args:
        - NODE_ENV=production
        - DATABASE_URL=${DATABASE_URL}
    ports:
      - "59991:3000"
    restart: unless-stopped
    
