services:
  frontend:
    build:
      context: ./frontend
      args:
        - NODE_ENV=production
        - DATABASE_URL=${DATABASE_URL}
        - NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
        - NEXT_PUBLIC_POSTHOG_HOST=${NEXT_PUBLIC_POSTHOG_HOST}
    ports:
      - "60001:3000"
    # networks:
    #   - nginxproxymanager_nginx-proxy-manager-nw
# networks:
#   nginxproxymanager_nginx-proxy-manager-nw: 
#     external: true

  