"""Initial migration for secondary DB

Revision ID: 0ae7dbb097bd
Revises: 
Create Date: 2024-11-10 02:46:11.563756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ae7dbb097bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('EntityTrait')
    # op.drop_table('_prisma_migrations')
    # op.drop_table('SurveyResponseItemReport')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SurveyResponseItemReport',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('responseItemId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('isDeleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=6), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=6), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['responseItemId'], ['SurveyResponseItem.id'], name='SurveyResponseItemReport_responseItemId_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='SurveyResponseItemReport_pkey')
    )

    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='_prisma_migrations_pkey')
    )

    op.create_table('EntityTrait',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entityId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('indicator', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=6), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=6), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['entityId'], ['Entity.id'], name='EntityTrait_entityId_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='EntityTrait_pkey')
    )

    # ### end Alembic commands ###
